import Head from 'next/head'
import Image from 'next/image'
import CanadaMap from '../components/CanadaMap'
import Facts from '../components/Facts'
import Flags from '../components/Flags'
import Title from '../components/Title'
import Languages from '../components/Languages'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Canadiana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    {/* <main className="main">
      <div className="wrapper">
        
        {provData !== undefined ? (
          <>
            <Facts {...{ provChoice, langChoice, provData }} />
            <Languages {...{ languageHandler }} />
            <Title {...{ provChoice, langChoice, provData }} />
            {CanadaMapMemo}
            <Flags {...{ provChoice, langChoice, provData, flagHandler }} />
          </>
        ) : null}

        <footer className="footer">
          <p>designed + developed by Stephen Korzenstein 2022</p>
        </footer>
      </div>
    </main> */}
  


  
    </div>
  )
}
